version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      W/p8e+jCxqtVpWHjtG7p3XW32VNb+8VV7rB/SOhDrZoDrsBXvKl7VfGDpc0Ars5uJ0WjmF8Z73EfX8c8UivEKzV+8ZRI5bxNWnOLhZxYcpzsnb997tvR4p6281SEX1qs761VO2fAP/BD2dpznxBOgDtTUiqrUCUdAiEahp1Qiiwff2XfPUMvC5T/Cb81Ggl9U5xsZFJodkb4TxEUPaDXGboDFuCxRrxNsIu861NOgVErqrWD+kKBQGQvG84sznPBrvJfXHgYfPPAYN+WH65B3helDu2dcVBrOXl5nZEEmtc2YZxQFM98pPSfAzqJRK4lIIbfLdmTY1Zy08R9bF3/I3/c56ataAduOEyzeTyq6jU+f4Ww+Zfs0qo5Wjbq0pNKACdHtW7D3jESRr3WnH5KWWQhRaIn5n++RArImkPT/rY7PJgeMfNZE0ipGmNuXXVlXw/ibnndTv+3e43VFtJArVHCXTrO5L31BRPNQHzAYEPJRA+/zzDQYeeTUj5BW9QXIo0TADTfApyngTnyDuP1DCc/D8WvuSmdUdt4O9Nw6s9QnwknbBM8rWqzolqEmvF8KJXOS/apveh6kTqnu/V5pG1mIygYL47IRrG9+9xT3Mr1p9QUe5vg7ca31nyLeBUbMQ93636RLUV5Cva3e8cBlokeJ1alb5OqnAEOtLJx2JU=
