version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      S42IcwUwjwcogaIFrHEbOoG+FSvXaIMqoB2za28U+WSYl/9NpqSiYOHF8yryFsDbeyD5XffvaudTuHXKX5ZMc06oPyb3UwTVtg9A8Sa/YrWnZ4GMJqMZ3/7Z9l3xvWryH9Cht6Rqa5cKqkrch32bT8d904QL97vHfh8ov1Yus3G1W064ZCuQOWSc/xRxSdXE9zKqotkCKA6RSi3FXckDH+pNYA2dG8qRt2we117vDJz5ZCGd3MxFUtM2m6iDy8KSn7beT2POMVvhG8xUuRZwo56wG2HJ9gDiHeSBDqAjHehCJpObpNA4z93289bXeHm9y3TyBoJfGwwPjsEKCiQ8EGGMsbE+0laLsiVFQ/+F8pnq5G3m0TxEoGzN1gLy5ZD7ECheVq6SHYtMpJzeortyZogzJUsgcJmwMSMkewDCL1s165vLmT6o1qQ5TmRE8ZtFCEMTe03PYDZ90UbVoPA4JyeFl4bCp4d93FjWzAYME55RBFcJmboOEDlsDTYvs5JLriD/DJS2xFD/TfuBGEVNRxb/98D6ZtAI4fMEfOFl7m7DUelljxFczKIIrLXQis54VA3ZVQpKVK4pV/H9nSR3uR7V6WRPa5ASA/wiRlFrpVVW7d1PSwBB+rJKQbkaKDhzzz+qqghydYMDsHcZ17QNUIXlNwXc+gPra6bl9kL87b4=
