version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      gLY4Dzd3KU5pOE6pjBX2x1jTc6OzqYma0xTo+mM98tWpzcYTiy0O8PR7HSZ5dzdrzGG+gZylrbjUgYLu0ari+jCrK8cC1yKAxrtAY2wkSDI6pR9clmlUougBEADvT56g5X/4qMf37L2G6DjqJSp1mK9/OCengOytNvTes92/OlzFidEx0/P4CTd+H37YBmuSYsFQ2trfNWG0p6altC35LbWzmDq7iyiRbu7RgGIHpTShXYadIiHkpWqG7cGGngzYjctRJMbYp+IBywH9wMaXPrsw0jr3kKimYvrVKK0umzxn5w52xYgC7AX7DKvsYQmPAV1yGcY27aM/bMhHrcj5gNhelNw4Gi51iLWhtIPLmVIIUv1TEDkUz1KOo32OW1SYZ1QO62N3GB406ZO9hMi/5Yu+Y09ZmQ2xAknIoVwntMQtiCzHE1CDUoSZ8GWvIKKf8nGhBWTvtqbEd+uFEu6CSVT1RlYNqyDzLfGTl0MTT38/a9d2G8jEepbZmPrV5YNYmZ4Dnfc9ZrdWNXh3nShtqkWbIWq5zv5Cf4S0hX6ApWmfQPDJEHwa7waZNoRGiU8UzXOgTapQfX3mH/ciskLWF09JCa+NPyNM23IIRirmswyveenHizN5n4C2zjSAR5LyNwM2hv46b+PEB+ZQ1PHAJfcgvdN+UjIBkUEGrilgG4w=
